"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import poselcm.pose_t

class pose_list_t(object):
    __slots__ = ["timestamp", "n", "poses"]

    def __init__(self):
        self.timestamp = 0
        self.n = 0
        self.poses = []

    def encode(self):
        buf = BytesIO()
        buf.write(pose_list_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.timestamp, self.n))
        for i0 in range(self.n):
            assert self.poses[i0]._get_packed_fingerprint() == poselcm.pose_t._get_packed_fingerprint()
            self.poses[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != pose_list_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return pose_list_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = pose_list_t()
        self.timestamp, self.n = struct.unpack(">qi", buf.read(12))
        self.poses = []
        for i0 in range(self.n):
            self.poses.append(poselcm.pose_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if pose_list_t in parents: return 0
        newparents = parents + [pose_list_t]
        tmphash = (0x9309d316bc1b349+ poselcm.pose_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if pose_list_t._packed_fingerprint is None:
            pose_list_t._packed_fingerprint = struct.pack(">Q", pose_list_t._get_hash_recursive([]))
        return pose_list_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

