"""LCM package __init__.py file
This file automatically generated by lcm-gen.
DO NOT MODIFY BY HAND!!!!
"""

from .timestamped_waypoint_t import timestamped_waypoint_t
from .timestamped_waypoint_list_t import timestamped_waypoint_list_t
