"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class timestamped_waypoint_t(object):
    __slots__ = ["timestamp", "position", "orientation"]

    def __init__(self):
        self.timestamp = 0
        self.position = [ 0 for dim0 in range(3) ]
        self.orientation = [ 0 for dim0 in range(4) ]

    def encode(self):
        buf = BytesIO()
        buf.write(timestamped_waypoint_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>3i', *self.position[:3]))
        buf.write(struct.pack('>4h', *self.orientation[:4]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != timestamped_waypoint_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return timestamped_waypoint_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = timestamped_waypoint_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.position = struct.unpack('>3i', buf.read(12))
        self.orientation = struct.unpack('>4h', buf.read(8))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if timestamped_waypoint_t in parents: return 0
        tmphash = (0x786cc1e1980915b5) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if timestamped_waypoint_t._packed_fingerprint is None:
            timestamped_waypoint_t._packed_fingerprint = struct.pack(">Q", timestamped_waypoint_t._get_hash_recursive([]))
        return timestamped_waypoint_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

